VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "Comment"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public lngSampleID As Double
Public Biochemistry As String
Public Haematology As String
Public Coagulation As String
Public Demographics As String
Public Immunology As String
Public Endocrinology As String
Public BloodGas As String
Public Semen As String
Public MicroCS As String
Public MicroGeneral As String
Public MicroIdent As String
Public MicroConsultant As String
Public Film As String
