Attribute VB_Name = "modOptionSettings"
Option Explicit

Public Function SaveOptionSetting(ByVal Description As String, _
                                  ByVal Contents As String)

      Dim tb As Recordset
      Dim sql As String

10    On Error GoTo SaveOptionSetting_Error

      'Created on 01/02/2011 16:59:49
      'Autogenerated by SQL Scripting

20    sql = "If Exists(Select 1 From Options " & _
          "Where Description = '@Description0' ) " & _
      "Begin " & _
          "Update Options Set " & _
          "Description = '@Description0', " & _
          "Contents = '@Contents1' " & _
          "Where Description = '@Description0'  " & _
      "End  " & _
      "Else " & _
      "Begin  " & _
          "Insert Into Options (Description, Contents) Values " & _
          "('@Description0', '@Contents1') " & _
      "End"

30    sql = Replace(sql, "@Description0", Description)
40    sql = Replace(sql, "@Contents1", Contents)

50    Cnxn(0).Execute sql

      'sql = "SELECT * FROM Options WHERE " & _
      '      "Description = '" & Description & "'"
      'Set tb = New Recordset
      'RecOpenServer 0, tb, sql
      'If tb.EOF Then
      '    tb.AddNew
      'End If
      'tb!Description = Description
      'tb!Contents = Contents
      'tb.Update

60    Exit Function

SaveOptionSetting_Error:

      Dim strES As String
      Dim intEL As Integer

70    intEL = Erl
80    strES = Err.Description
90    LogError "modOptionSettings", "SaveOptionSetting", intEL, strES, sql

End Function


Public Function GetOptionSetting(ByVal Description As String, _
                                 ByVal Default As String) As String

      Dim tb As Recordset
      Dim sql As String
      Dim RetVal As String

10    On Error GoTo GetOptionSetting_Error

20    sql = "SELECT Contents FROM Options WHERE " & _
            "Description = '" & Description & "'"
30    Set tb = New Recordset
40    RecOpenServer 0, tb, sql
50    If tb.EOF Then
60        RetVal = Default
70    ElseIf Trim$(tb!Contents & "") = "" Then
80        RetVal = Default
90    Else
100       RetVal = tb!Contents
110   End If

120   GetOptionSetting = RetVal

130   Exit Function

GetOptionSetting_Error:

      Dim strES As String
      Dim intEL As Integer

140   intEL = Erl
150   strES = Err.Description
160   LogError "modOptionSettings", "GetOptionSetting", intEL, strES, sql

End Function


